### ISSUE TITLE
Option to force expiration evaluation on startup

### ISSUE THREAD

**Issue by SrBedrock** [GPAddons/GPClaimExpiration#1]
I have thousands of protections that should already be abandoned and I would like to be able to activate an option that would check all protections saved at startup.

**Comment by Jikoo** [comment]
So for clarity, how is GPCE running? Everything seems normal in logs, claims actually being removed? This seems like a one-time-use sort of feature that would be resolved by making sure every claim is considered within the time between restarts. If it's not intended to be one-time-use you're just blocking players from rejoining your server for longer while something that could occur naturally during uptime takes place.

If you urgently need to consider all players, could you try setting percent value to 1000 temporarily or something? That would ensure that all players with claims are considered in 6 minutes, after which you could revert to less-aggressive settings.

If you are seeing claims that should be expired after GPCE finishes a run, please enable debug logging in GP (GPCE piggybacks its abridged log system) and pass me the results, I really want to make sure there's some functional periodic expiration system available for GP.

**Comment by SrBedrock** [comment]
> So for clarity, how is GPCE running? Everything seems normal in logs, claims actually being removed? 

Nothing is being displayed in the log regarding GPClaimExpiration, only when the plugin is activated at the start of the server, should something be displayed when the protections are removed? I will activate griefprevention debug mode to see if something is displayed.

>  This seems like a one-time-use sort of feature that would be resolved by making sure every claim is considered within the time between restarts. If it's not intended to be one-time-use you're just blocking players from rejoining your server for longer while something that could occur naturally during uptime takes place.

This is the idea, something that would be activated once every year during the start of the server for example and not something that would be on all the time.

> If you urgently need to consider all players, could you try setting percent value to 1000 temporarily or something? That would ensure that all players with claims are considered in 6 minutes, after which you could revert to less-aggressive settings.

Like this:
```yml
expiration:
  evaluation:
    rate:
      # Check types: PERCENT, COUNT
      type: PERCENT
      value: 1000
    random: false
  days_per_area:
    250000: 100
    10000: 90
    100: 60
    0: 30
  bypass:
    claim_blocks: -1
    bonus_claim_blocks: -1
    permissions:
      - gpclaimexpiration.persist
  # Command placeholders: $playerName, $playerUUID, $world, $locX, $locY, $locZ
  # Additional delete command placeholders: $claimId, $locMaxX, $locMaxY, $locMaxZ, $area
  claim.commands: []
  pet:
    days: 30
    commands: []
```

> If you are seeing claims that should be expired after GPCE finishes a run, please enable debug logging in GP (GPCE piggybacks its abridged log system) and pass me the results, I really want to make sure there's some functional periodic expiration system available for GP.

As I am not finding anything in the server log that indicates the functioning of GPClaimExpiration, I will activate the function before performing the procedure recommended above.
